apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "defiant-kube.fullname" . }}
  labels:
    {{- include "defiant-kube.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "defiant-kube.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "defiant-kube.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "defiant-kube.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.vars.healthCheckPort }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.vars.applicationPort }}
              protocol: UDP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            - name: APPLICATION_PORT
              value: {{ .Values.applicationPort }}
            - name: MAX_SEND_ATTEMPTS
              value: {{ .Values.maxSendAttempts }}
            - name: BASE_RETRY_DELAY_MS
              value: {{ .Values.baseRetryDelayMs }}
            - name: CLIENT_RPC_PORT
              value: {{ .Values.clientRpcPort }}
            - name: MEMBERSHIP_PORT
              value: {{ .Values.membershipPort }}
            - name: HEALTH_CHECK_PORT
              value: {{ .Values.healthCheckPort }}
            - name: DNS_NAMESPACE
              value: {{ .Values.dnsNamespace }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
